# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
target '撕麦耳微搏' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'MJRefresh'

end

